version: '7.9.3'

services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch-node1                             # Name of the first Elasticsearch container
    environment:
      - node.name=es-node1                                          # Unique name for the Elasticsearch node
      - cluster.name=cv-cluster                                     # Name of the Elasticsearch cluster
      - discovery.seed_hosts=elasticsearch-node2                    # Hostname of other nodes for cluster discovery
      - cluster.initial_master_nodes=es-node1,elasticsearch-node2   # Initial master nodes for the cluster
      - bootstrap.memory_lock=false                                 # Disable memory locking (changed from true for development purposes)
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"                                # Set minimum and maximum JVM heap size to 1GB
      - xpack.security.enabled=false                                # Disable X-Pack security features for simplicity
    ulimits:
      memlock:
        soft: -1   # Remove soft limit on memory locking
        hard: -1   # Remove hard limit on memory locking
    volumes:
      - esdata-node1:/usr/share/elasticsearch/data                  # Mount persistent storage for Elasticsearch data
    ports:
      - 9200:9200  # Expose Elasticsearch HTTP port to the host machine
    networks:
      - esnet      # Connect the container to the 'esnet' network

  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch-node2                             # Name of the second Elasticsearch container
    environment:
      - node.name=elasticsearch-node2                               # Unique name for the Elasticsearch node
      - cluster.name=cv-cluster                                     # Name of the Elasticsearch cluster (must match node1)
      - discovery.seed_hosts=elasticsearch-node1                    # Hostname of other nodes for cluster discovery
      - cluster.initial_master_nodes=es-node1,elasticsearch-node2   # Initial master nodes for the cluster
      - bootstrap.memory_lock=false                                 # Disable memory locking (changed from true for development purposes)
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"                                # Set minimum and maximum JVM heap size to 1GB
      - xpack.security.enabled=false                                # Disable X-Pack security features for simplicity
    ulimits:
      memlock:
        soft: -1   # Remove soft limit on memory locking
        hard: -1   # Remove hard limit on memory locking
    volumes:
      - esdata-node2:/usr/share/elasticsearch/data                  # Mount persistent storage for Elasticsearch data
    networks:
      - esnet      # Connect the container to the 'esnet' network

  search-ui:
    image: elasticsearch/search-ui:latest                           # Replace with the appropriate Search UI image
    container_name: search-ui                                       # Name of the Search UI container
    ports:
      - 3000:3000  # Expose Search UI on http://localhost:3000/
    environment:
      - SEARCH_UI_ELASTICSEARCH_URL=http://elasticsearch-node1:9200  # URL of the Elasticsearch cluster
      - SEARCH_UI_INDEX=cv-transcriptions                            # Elasticsearch index to search
      - SEARCH_UI_FIELDS=generated_text,duration,age,gender,accent   # Fields to enable for search
    depends_on:
      - elasticsearch-node1
      - elasticsearch-node2
    networks:
      - esnet      # Connect the container to the 'esnet' network

volumes:
  esdata-node1:
    driver: local  # Use the local Docker volume driver for node1 data persistence
  esdata-node2:
    driver: local  # Use the local Docker volume driver for node2 data persistence

networks:
  esnet:
    driver: bridge # Define a bridge network named 'esnet' for Elasticsearch nodes to communicate